version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: 'Mongodb'
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - Pim
    ports:
      - '27017:27017' 

  crude:
    image: crud:v6
    container_name: 'CrudeMongo'
    networks:
      - Pim
    volumes:
      - ./crude-vol:/usr/src

  VueServ:
    image: vue:v1
    container_name: 'Site Web'
    networks:
      - Pim
    volumes:
      - ./site-webdata:/www
    working_dir: /www
    ports:
      - 8080:8080
    
    

networks:
  Pim:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          aux_addresses:
             mongodb : 10.5.0.5
             CrudeMongo : 10.5.0.6
             
